### ISSUE TITLE
Website PageFlow and Page Layouts

### ISSUE THREAD

**Issue by adamsm6** [andywu9/StudyBuddy#2]
**Sign In page**- username,password, leads to main page
**Create Account page**- Allow users to register an account on study buddy using RPI email
**Main Page**- Displays a personalized greeting message and links to your courses
**Profile page**- Shows users profile and their weekly/daily calendar of events
**Settings Page**- Allows users to edit their profile or delete account
**Course Page**- Shows group messages among students in class and private groups within the class
**Analytics/Timer Page**- Page that displays charts of users study times and has a timer that can be started to time a study session
**Edit Course Page**- Allow users to select courses to add or drop current courses

**Comment by andywu9** [comment]
Finished: check Diagrams folder in repo.
